
/* MotoCoder_ModuleSupport_CAN.c */
/* Generated by MotoCoder */
/* Version: 0.12.4 */
/* At: 2018-09-04 13:38:00 */
/* Copyright: 2018 Woodward. */


#include <MotoCoder.h>
#include <MotoCoder_ModuleSupport_CAN.h>

/* MotoCoder_ModuleSupport_CAN */
/*---- DEFINES --------------------------------------------------------------------------------------------*/    

/*---- TYPEDEF --------------------------------------------------------------------------------------------*/

/*---- FUNCTION PROTOTYPES --------------------------------------------------------------------------------*/

/*---- EXTERNALS ------------------------------------------------------------------------------------------*/

/*---- CONSTANTS ------------------------------------------------------------------------------------------*/
#include <Pragma_Section_Start_CC_rodata.h>

#include <Pragma_Section_End_rodata.h>

/*---- CALIBRATION ----------------------------------------------------------------------------------------*/

/*---- RAM VARIABLES --------------------------------------------------------------------------------------*/
#include <Pragma_Section_Start_CC_bss.h>

#include <Pragma_Section_End_bss.h>

/*---- INITIALIZED RAM VARIABLES --------------------------------------------------------------------------*/
#include <Pragma_Section_Start_CC_data.h>

#include <Pragma_Section_End_data.h>

/*---- LOCAL FUNCTIONS ------------------------------------------------------------------------------------*/
#include <Pragma_Section_Start_CC_Code.h>

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::`:::::::::::
:: ModuleSupport_KeySuiteSupport_CloseNonProgrammingCANLinks
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*! \brief This function is invoked upon the change of application execution, namely the jump from user 
    application to hardboot, due to a Keysuite command or instruction. Its goal is to allow the module support
    layer of a module family its last and final chance to close any open CAN links before application execution 
    is terminated. 
    
    \param in_u8AllowConnectOnCANMask The mask which indicates what CAN channels will be utilized during any
	subsequent programming over CAN.

	\remarks This function and its implementation is module-family specific.  In this case, the 55xx family
	does not close any CAN links.  It should be known that this function runs subsequent to the 
	ModuleSupport_Close and IO_Stop calls which are invoked by MotoCoder itself.
*/
void ModuleSupport_KeySuiteSupport_CloseNonProgrammingCANLinks(uint8_T in_u8AllowConnectOnCANMask)
{
	/* At this time, the 55xx family does not close any CAN links in this context */
}

#include <Pragma_Section_End_Code.h>

