
/* MotoCoder_ToolInterface.c */
/* Generated by MotoCoder */
/* Version: 0.12.4 */
/* At: 2018-08-25 21:19:47 */
/* Copyright: 2018 Woodward. */


#include <MotoCoder_Types.h>
#include <ModuleConfig_API.h>
#include <MotoTronBootObj_API.h>
#include <MotoCoder_Callbacks.h>



/* --- TYPEDEF --------------------------------------------------------------------------------------------*/

/* --- FUNCTION PROTOTYPES --------------------------------------------------------------------------------*/

/* --- CONSTANTS ------------------------------------------------------------------------------------------*/
    
/* Name: project_id CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 
Gain:1 Min:0 Max:255 Format:3.0 UpdateID:REMOTE Struct:g_eProjectID Group:"System | Version" 
Help:"This is the Platform ID used by the tools." */
const uint8_T g_eProjectID = 6;

/* Name: ProductID CType:uint32_T Unit:ID ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT4 
Gain:1 Min:0.00 Max:4294967296.00 Format:10.0 UpdateID:REMOTE Struct:g_u4ProductID Group:"System | Version"
Help:"Customer's ID used by the tools." */
const uint32_T g_u4ProductID = 1;

/* Name: SwIdTxt ClassID:TEXT StorageID:CODE Access:RO4+RO3+RO2+RO1 UpdateID:ONCE TextLen:13
Group:"System | Version" Help:"Software Format ID" */
const uint8_T SwIdTxt[13] =  /*  Mooventur_214  */  
 	 {  'M','o','o','v','e','n','t','u','r','_','2','1','4'  } 
;

/* Name: SwRevisionTxt ClassID:TEXT StorageID:CODE Access:RO4+RO3+RO2+RO1 UpdateID:ONCE TextLen:50
Group:"System | Version" Help:"Software Revision ID" */
const uint8_T SwRevisionTxt[50] = "Mooventure2016_Rev5_214";

/* Name: FriendlyName ClassID:TEXT StorageID:CODE Access:RO4+RO3+RO2+RO1 UpdateID:REMOTE 
TextLen:33 Group:"System | Version" Help:"The device's friendly name." */
const uint8_T FriendlyName[33] = "";
    
/* Name: table_0_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table0Rev_cu1 Group:"System | Tool Interface" Help:"This is Table0 Revision Number" */
const uint8_T Table0Rev_cu1 = 9;

/* Name: table_1_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table1Rev_cu1 Group:"System | Tool Interface" Help:"This is Table1 Revision Number" */
const uint8_T Table1Rev_cu1 = 1;

/* Name: table_2_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table2Rev_cu1 Group:"System | Tool Interface" Help:"This is Table2 Revision Number" */
const uint8_T Table2Rev_cu1 = 1;

/* Name: table_3_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table3Rev_cu1 Group:"System | Tool Interface" Help:"This is Table3 Revision Number" */
const uint8_T Table3Rev_cu1 = 1;      

/* Name: table_4_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table4Rev_cu1 Group:"System | Tool Interface" Help:"This is Table4 Revision Number" */
const uint8_T Table4Rev_cu1 = 1;

/* Name: table_5_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table5Rev_cu1 Group:"System | Tool Interface" Help:"This is Table5 Revision Number" */
const uint8_T Table5Rev_cu1 = 1;

/* Name: table_6_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table6Rev_cu1 Group:"System | Tool Interface" Help:"This is Table6 Revision Number" */
const uint8_T Table6Rev_cu1 = 1;

/* Name: table_7_rev CType:uint1 ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
    Max:255 Format:3.0 UpdateID:ONCE Struct:Table7Rev_cu1 Group:"System | Tool Interface" Help:"This is Table7 Revision Number" */
const uint8_T Table7Rev_cu1 = 1;




/* Name: MotProgRev CType:uint8_T ClassID:VAR StorageID:CODE Access:RO4+RO3+NA2+NA1 TypeID:UINT1 Gain:1 Min:0 
Max:255 Format:3.0 UpdateID:ONCE Struct:g_Protocol_MotProg_Rev Group:"System | Tool Interface"
Help:"MotoTron Programming Interface Version" */

/* Name: Protocol_KeySuite_Rev CType:uint8_T ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 
Gain:1 Min:0 Max:255 Format:3.0 UpdateID:ONCE Struct:g_Protocol_Key_Rev Group:"System | Tool Interface" 
Help:"MotoTron KeySuite Protocol Version (Key/ERI)" */

/* Name: EriRev CType:uint8_T ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 
Max:255 Format:3.0 UpdateID:ONCE Struct:g_Protocol_ERI_Rev Group:"System | Tool Interface"
Help:"This is the revision for the ERI protocol." */


/* Name: BootVerMaj CType:uint8_T ClassID:VAR StorageID:RAM Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0
Max:255 Format:3.0 Struct:g_u8BootVerMaj Group:"System | Module" */
uint8_T g_u8BootVerMaj;

/* Name: BootVerMin CType:uint8_T ClassID:VAR StorageID:RAM Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0
Max:255 Format:3.0 Struct:g_u8BootVerMin Group:"System | Module" */
uint8_T g_u8BootVerMin;

/* Name: EcuHwMaj CType:uint8_T ClassID:ENUMVAR EnumDec:E_MotoTronModuleHwMaj StorageID:RAM
Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0 Max:255 Format:3.0 Struct:g_eEcuHwMaj
Group:"System | Module" */
uint8_T g_eEcuHwMaj;

/* Name: EcuHwMin CType:uint8_T ClassID:VAR StorageID:CODE Access:RO4+RO3+RO2+RO1 TypeID:UINT1 Gain:1 Min:0
Max:255 Format:3.0 Struct:g_u8EcuHwMin Group:"System | Module" */
uint8_T g_u8EcuHwMin;

/* Name: Capability CType:uint8_T ClassID:ENUMVAR StorageID:RAM Access:RO4+RO3+NA2+NA1 TypeID:UINT1 Gain:1 
   Min:0 Max:255 Format:4.0 UpdateID:BACKGND Struct:g_u8Capability EnumDec:E_ModuleCapability Group:"System | "
   "Module" VardecSig:6C */
uint8_T g_u8Capability;

char const s_szBadString[] = "Bad";

/* Name: SerialNumber CType:char ClassID:TEXT_PTR StorageID:CODE Access:RO4+RO3+RO2+RO1
Struct:g_pszSerialNumber TextLen:49 Group:"System | Module" Help:"Module Serial Number" */
char const*  g_pszSerialNumber;

/* Name: PartNumber CType:char ClassID:TEXT_PTR StorageID:CODE Access:RO4+RO3+RO2+RO1
Struct:g_pszPartNumber TextLen:40 Group:"System | Module" Help:"Module Part Number" */
char const*  g_pszPartNumber;

/* Name: ModelNumber CType:char ClassID:TEXT_PTR StorageID:CODE Access:RO4+RO3+RO2+RO1
Struct:g_pszModelNumber TextLen:49 Group:"System | Module" Help:"Module Model Number" */
char const*  g_pszModelNumber;

/* Name: ApplicationCompatibilityArr ClassID:ARRAY Access:RO4+RO3+RO2+RO1 StorageID:CODE UpdateID:ONCE
TypeID:UINT2 Gain:1 Offset:0.0 Exp:1.0 Max:65535 Min:0 Format:5.0 Mask:0000FFFF CType:uint16_T
Struct:ApplicationCompatibilityArr[0] Help:"Software Format ID" Group:"System | Module" XLen:1 YLen:50 */

/* --- LOCAL FUNCTIONS ------------------------------------------------------------------------------------*/
void ReadModuleConfig(void)
{   

	BASEPTRARR pModuleDefnArray;
    S_ModuleConfigDefn const* __FAR_POINTER pModuleDefn;
	uint32_T* __FAR_POINTER pVersion;
    
	/* Init defaults - in case we can't find a module definition */
    g_pszSerialNumber = s_szBadString;
    g_pszPartNumber = s_szBadString;
    g_pszModelNumber = s_szBadString;
    g_eEcuHwMaj = 0x11;
    g_u8EcuHwMin = 7;
    g_u8Capability = 0;

    /* Recover the version of the ModuleDefn array, which is always a pointer in the 1st entry */
    pModuleDefnArray = GetModuleConfigPointerArr();
    pVersion = (uint32_T* __FAR_POINTER) pModuleDefnArray[0];

	/* Do some address range check on pVersion here... */
	pModuleDefn = NULL;
	if (pVersion != (uint32_T* __FAR_POINTER)0xFFFFFFFF)
	{
		/* Try find a module defn */
	    switch(*pVersion)
	    {
		    case PV0:
			    /* Recover a pointer to the Module Definition object */
	            pModuleDefn = (S_ModuleConfigDefn const* __FAR_POINTER)pModuleDefnArray[MC_PV0_S_CONFIGURATIONDEFN];
				break;

		    case PV1:
			    /* Recover a pointer to the Module Definition object */
	            pModuleDefn = (S_ModuleConfigDefn const* __FAR_POINTER)pModuleDefnArray[MC_PV1_S_CONFIGURATIONDEFN];
				break;
		}
	}

	/* Did we find a module definition? */
	if (pModuleDefn)
	{
	    uint32_T uVersion;

        /* Get the version of this object */
        uVersion = pModuleDefn->u4Version;
        if (pModuleDefn->pModuleConfig)
        {
            switch(uVersion)
            {
		        case PV0:
		        {
		            S_ModuleConfigV0  const* __FAR_POINTER pModuleConfig = (S_ModuleConfigV0 const* __FAR_POINTER)pModuleDefn->pModuleConfig;
		            
		            g_pszSerialNumber = (char const*)(uint32_T)pModuleConfig->SerialNumber;
		            g_pszModelNumber = (char const*)(uint32_T)pModuleConfig->ModelNumber;
		            g_eEcuHwMaj = pModuleConfig->EcuHwMaj;
		            g_u8EcuHwMin = pModuleConfig->EcuHwMin;
		            g_u8Capability = pModuleConfig->Capability;
		            break;
	            }

		        case PV1:
		        {
		            S_ModuleConfigV1  const* __FAR_POINTER pModuleConfig = (S_ModuleConfigV1 const* __FAR_POINTER)pModuleDefn->pModuleConfig;
		            
		            g_pszSerialNumber = (char const*)(uint32_T)pModuleConfig->SerialNumber;
		            g_pszModelNumber = (char const*)(uint32_T)pModuleConfig->ModelNumber;
		            g_eEcuHwMaj = pModuleConfig->EcuHwMaj;
		            g_u8EcuHwMin = pModuleConfig->EcuHwMin;
		            g_u8Capability = pModuleConfig->Capability;
		            break;
	            }

		        case PV2:
		        {
		            S_ModuleConfigV2  const* __FAR_POINTER pModuleConfig = (S_ModuleConfigV2 const* __FAR_POINTER)pModuleDefn->pModuleConfig;
		            
		            g_pszSerialNumber = (char const*)(uint32_T)pModuleConfig->SerialNumber;
		            g_pszModelNumber = (char const*)(uint32_T)pModuleConfig->ModelNumber;
		            g_eEcuHwMaj = pModuleConfig->EcuHwMaj;
		            g_u8EcuHwMin = pModuleConfig->EcuHwMin;
		            g_u8Capability = pModuleConfig->Capability;
		            break;
	            }

		        case PV3:
		        {
		            S_ModuleConfigV3  const* __FAR_POINTER pModuleConfig = (S_ModuleConfigV3 const* __FAR_POINTER)pModuleDefn->pModuleConfig;
		            
		            g_pszSerialNumber = (char const*)(uint32_T)pModuleConfig->SerialNumber;
		            g_pszPartNumber = (char const*)(uint32_T)pModuleConfig->PartNumber;
		            g_pszModelNumber = (char const*)(uint32_T)pModuleConfig->ModelNumber;
		            g_eEcuHwMaj = pModuleConfig->EcuHwMaj;
		            g_u8EcuHwMin = pModuleConfig->EcuHwMin;
		            g_u8Capability = pModuleConfig->Capability;
		            break;
	            }

	            case PV4:
                {
                    S_ModuleConfigV4 const * __FAR_POINTER pModuleConfig = (S_ModuleConfigV4 const* __FAR_POINTER)pModuleDefn->pModuleConfig;
					g_pszSerialNumber = (char const*)(uint32_T)pModuleConfig->SerialNumber;
					g_pszPartNumber = (char const*)(uint32_T)pModuleConfig->PartNumber;
					g_pszModelNumber = (char const*)(uint32_T)pModuleConfig->ModelNumber;
					g_eEcuHwMaj = pModuleConfig->EcuHwMaj;
					g_u8EcuHwMin = pModuleConfig->EcuHwMin;
					g_u8Capability = pModuleConfig->Capability;
					break;
	            }

	            case PV5:
                {
                    S_ModuleConfigV5 const * __FAR_POINTER pModuleConfig = (S_ModuleConfigV5 const* __FAR_POINTER)pModuleDefn->pModuleConfig;
					g_pszSerialNumber = (char const*)(uint32_T)pModuleConfig->V3.SerialNumber;
					g_pszPartNumber = (char const*)(uint32_T)pModuleConfig->V3.PartNumber;
					g_pszModelNumber = (char const*)(uint32_T)pModuleConfig->V3.ModelNumber;
					g_eEcuHwMaj = pModuleConfig->V3.EcuHwMaj;
					g_u8EcuHwMin = pModuleConfig->V3.EcuHwMin;
					g_u8Capability = pModuleConfig->V3.Capability;
					break;
	            }

		        default:
					break;
		    }
        }
	}

	/* Lastly - try get the hard boot version */
	MotoTronBoot_Version_GetFromHardBoot(&g_u8BootVerMaj, &g_u8BootVerMin);
	
}
      

    
/*----- END OF FILE ---------------------------------------------------------------------------------------*/



