
/* file:/C:/Users/maxar/Documents/GitHub/Wisconsin-Hybrid/BatteryController_Rev1/BatteryController_Rev1_Build/TDB/TableDB.c */
/* Generated by MotoCoder */
/* Version: 0.12.4 */
/* At: 2018-09-07 09:43:39 */
/* Copyright: 2018 Woodward. */





#define  NO_TDB_PARSE
	
#define __TABLEDB_C
#define __TABLEDB_TDB
	


/* --- INCLUDE FILES --------------------------------------------------------------------------------------*/
	    
 #include "CommonInclude.h"
 #include "BatteryController_Rev1.h"
 #include "TDB_Includes.h"
 
 

/* --- DEFINES -------------------------------------------------------------------------------------------*/
#ifndef __FAR_POINTER
    /* Define __FAR_POINTER as nothing */
    #define __FAR_POINTER
#endif
	    
/* var*/ 
 extern uint1 g_eProjectID;
 extern uint1 Table0Rev_cu1;
 extern uint1 Table1Rev_cu1;
 extern uint1 Table2Rev_cu1;
 extern uint1 g_u1KeyRev;
 extern uint1 g_u1EriRev;
 extern uint1 Table3Rev_cu1;
 extern uint1 Table4Rev_cu1;
 extern uint1 Table5Rev_cu1;
 extern uint1 Table6Rev_cu1;
 extern uint1 Table7Rev_cu1;
 extern uint4 g_u4ProductID;
 extern uint1 g_u1MotProgRev;
 extern S_ModuleConfig g_ConfigCopyObj;
 extern Volatile_BSS_T VolatileWork_BSS;
 extern NonVolatile_T NonVolatileWork;
 extern BlockIO_BatteryController_Rev1 BatteryController_Rev1_B;
 extern const Constant_T ConstantWork;
 extern int32_T BGND_BASE_PERIODIC_RunCnt;
 extern int32_T BGND_BASEx10_PERIODIC_RunCnt;
 extern int32_T BGND_BASEx2_PERIODIC_RunCnt;
 extern uint2 BgndStackMargin;
 extern uint4 g_pBgndStackMinBytesFree;
 extern uint2 g_pu2IdlePerfTimerValue;
 extern uint2 CPUMargin;
 extern uint2 g_pCPUTime_AppISR;
 extern uint2 g_pu2BgndPerfTimerValue;
 extern uint2 g_pCPUTime_CAN;
 extern uint2 g_pu2FgndAnglePerfValue;
 extern uint2 g_pu2FgndTimePerfTimerValue;
 extern uint2 g_pCPUTime_MIOS;
 extern uint2 g_pCPUTime_Serial;
 extern uint2 g_pCPUTime_TimerISR;
 extern uint2 g_pCPUTime_TPU;
 extern int32_T FGND_10XRTI_PERIODIC_RunCnt;
 extern int32_T FGND_20XRTI_PERIODIC_RunCnt;
 extern int32_T FGND_2XRTI_PERIODIC_RunCnt;
 extern int32_T FGND_RTI_PERIODIC_RunCnt;
 extern uint4 g_pu4FgndAngleStackMinBytesFree;
 extern uint2 FgndTimeStackMargin;
 extern uint4 g_pFgndTimeStackMinBytesFree;
 extern uint2 HeapMargin;
 extern int32_T IDLE_EVENT_RunCnt;
 extern uint2 IdleStackMargin;
 extern uint4 g_pIdleStackMinBytesFree;
 extern uint2 InterruptStackMargin;
 extern uint2 g_u2InterruptStackMaxBytesFree;
 extern uint1 LinkStatus_ru1;
 extern uint32_T NonVolatile_NonVolatileCRC;
 extern int32_T ONE_SECOND_EVENT_RunCnt;
 extern uint1 OSInternalErrorCnt_ru1;
 extern uint4 g_u4PeakHeapBytesUsed;
 extern int32_T STARTUP_EVENT_RunCnt;
 extern uint1 g_pSWISRCurrQueueSize;
 extern uint4 SystemFrequency_cu4;
 extern uint1 g_u1TPUMaskVers;
 extern uint1 Unused_ru1;
 
 /* text*/ 
 extern uint1 SwIdTxt[];
 extern uint1 CalIdTxt[];
 extern uint1 SwRevisionTxt[];
 extern uint1 FriendlyName[];
 extern uint1 CompilerVersion[];
 extern uint1 ControlCoreSDKRelease[];
 extern uint1 MatlabVersionTxt[];
 extern uint1 MotoHawkBuildGUID[];
 extern uint1 MotoHawkModelGUID[];
 extern uint1 MotoHawkModelName[];
 extern uint1 MotoHawkTokenGUID[];
 extern uint1 MotoHawkVersionTxt[];
 extern uint1 PasswordTxt[];
 
 /* array*/ 
 extern S_HardwareCompatibilityEntry ApplicationCompatibilityArr[];
 
 /* enum*/ 
 extern E_NativeFWError ain_create_Current_Sensor;
 extern E_NativeFWError ain_create_ECUP;
 extern E_NativeFWError ain_create_V5V_Reference;
 extern E_NativeFWError ain_read_Current_Sensor;
 extern E_NativeFWError ain_read_ECUP;
 extern E_NativeFWError ain_read_V5V_Reference;
 extern E_ApplicationInitStatus ApplicationInitStatus;
 extern E_ApplicationMonitorEnable ApplicationMonitorEnable;
 extern E_ApplicationInitStatus ApplicationPausePoint;
 extern E_ApplicationStatus ApplicationStatus;
 extern uint32_T ApplicationStopReason;
 extern uint32_T ApplicationStopReasonBlock;
 extern uint2 g_u1BgndAngSchdLateFlags;
 extern uint1 g_u1BgndTimeSchdLateFlags;
 extern E_NativeFWError can_create_CAN_1;
 extern E_NativeFWError can_tx_err_CAN_1_0;
 extern E_NativeFWError dout_create_DOut2268p0004;
 extern E_NativeFWError dout_create_DOut953p0001;
 extern E_NativeFWError dout_create_DOut954p0001;
 extern E_NativeFWError dout_create_DOut955p0001;
 extern E_NativeFWError dout_create_DOut956p0001;
 extern uint2 g_u1FgndAngSchdLateFlags;
 extern S_SetDisplayInfo FWModulesSetDisplayInfo;
 extern E_OSInternalErrorType OSErrorDisplay;
 extern uint8_T NonVolatileRestoreOnFirstStartup;
 extern uint8_T NonVolatileRestoreOnStartup;
 extern uint8_T NonVolatile_NonVolatileStatus;
 extern E_OSStatus OSStatus;
 extern E_NativeFWError protocol_register_CAN_1;
 extern E_NativeFWError pwm_create_EST1_PWMOutput;
 extern E_NativeFWError pwm_set_EST1_PWMOutput;
 extern E_NativeFWError resource_allocation;
 extern uint1 g_eTPUMaskType;
 
 /* bitfield*/ 
 extern S_CCPHandlerInstance mh_CCP_BAT_CCPHandlerInstance;
 extern uint4 CodeCoveredBits[];
 
 /* prelookup*/ 
 
 /* interpolation_2d*/ 
 
 /* interpolation_1d*/ 
 


#include <Pragma_Section_Start_ERIToolsTable_rodata.h>

const S_EriRequestTable Table0[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table0Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table1Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table2Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_u1KeyRev, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_u1EriRev, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table3Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table4Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table5Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table6Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table7Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&SwIdTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 13, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&CalIdTxt[0], 0xC0+0x30+0x0C+0x03, 0, CLASS_TEXT, 33, FLASH, 0, 1, 1}, 
 {(void* __FAR_POINTER)&SwRevisionTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&FriendlyName[0], 0xC0+0x30+0x04+0x01, 0, CLASS_TEXT, 33, FLASH, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_u4ProductID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&g_u1MotProgRev, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.BootVerMaj, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.BootVerMin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.EcuHwMaj, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.EcuHwMin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationCompatibilityArr[0], 0x40+0x10+0x04+0x01, 0, CLASS_ARRAY, 50, CODE, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.psSerialNumber, 0x40+0x10+0x04+0x01, 1, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.psModelNumber, 0x40+0x10+0x04+0x01, 1, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 };

 const S_EriRequestTable Table1[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&VolatileWork_BSS.ActiveDTC_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.ActiveDTC_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.ActiveDTC_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ain_create_Current_Sensor, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_create_ECUP, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_create_V5V_Reference, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_Current_Sensor, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_ECUP, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_V5V_Reference, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Amp_Clamp_K, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Amp_Offset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.AMPCurrent_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.AMPCurrent_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s15_Product, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s15_Sum, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s20_amps, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.AmpIn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.AmpOut, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.AmpV_Offset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ApplicationInitStatus, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationMonitorEnable, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationPausePoint, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationStatus, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationStopReason, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ApplicationStopReasonBlock, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BalancingCount_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BalancingCount_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s43_ReadCANMessage1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Battery_Enable_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Battery_Enable_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BatteryCurrent_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BatteryCurrent_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s21_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BatteryVoltage_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BatteryVoltage_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s52_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s45_ReadCANMessage_o1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BGND_BASE_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&BGND_BASEx10_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&BGND_BASEx2_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&g_u1BgndAngSchdLateFlags, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BgndStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pBgndStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&g_u1BgndTimeSchdLateFlags, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BusVoltage_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.BusVoltage_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s52_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_ext_handled_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_ext_last_unhandled_id, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_ext_receive_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_std_handled_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_std_last_unhandled_id, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_std_receive_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&can_create_CAN_1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&can_tx_err_CAN_1_0, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP_BAT_StationAddr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP_BATRxID, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP_BATRxIDMask, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP_BATTxID, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&mh_CCP_BAT_CCPHandlerInstance.UnlockStatus, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&mh_CCP_BAT_CCPHandlerInstance.Connected, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CellBalancingActive_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CellBalancingActive_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s89_Compare, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CellTemp_PreLookupIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.CellTemp_PreLookupIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 7, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CellTemp_PreLookupIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.CityID_CAN_1, 0xC0+0x00+0x00+0x00, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[0], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[1], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[2], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[3], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[4], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil1_Neg_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil1_Neg_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s24_Negative, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil1_Pos_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil1_Pos_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s24_Positive, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil2_Pos_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil2_Pos_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s24_PreChargeCoil, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil3_Pos_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil3_Pos_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coil3_Pos_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&CompilerVersion[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.u1ConfigVerMaj, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.u1ConfigVerMin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ControlCoreSDKRelease[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.CoolantTemperature, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CoolantTemperature_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CoolantTemperature_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CoolantTemperature_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&g_pu2IdlePerfTimerValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&CPUMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_AppISR, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pu2BgndPerfTimerValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_CAN, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pu2FgndAnglePerfValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pu2FgndTimePerfTimerValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_MIOS, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_Serial, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_TimerISR, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_TPU, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Current_Div2, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Current_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Current_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s44_motohawk_ain, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s39_currState, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Delay_3_Cal, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Delay_5_Cal, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Delay3, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Delay5, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut2268p0004, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut953p0001, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut954p0001, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut955p0001, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut956p0001, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.DPI_RollingCounter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.DPI_RollingCounter_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.DPI_RollingCounter_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.DPI_RollingCounter_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.DutyCycle, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.DutyCycle_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.DutyCycle_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.DutyCycle_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.ECUP_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.FaultsDTC, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FaultsDTC_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FaultsDTC_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s43_ReadCANMessage, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&FGND_10XRTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&FGND_20XRTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&FGND_2XRTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&FGND_RTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&g_pu4FgndAngleStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&g_u1FgndAngSchdLateFlags, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&FgndTimeStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pFgndTimeStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&FWModulesSetDisplayInfo.DisplayVar, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.FreqEnd, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FreqEnd_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FreqEnd_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FreqEnd_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.FreqStart, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FreqStart_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FreqStart_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FreqStart_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.G_Sensativity, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&HeapMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.highAmperage, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.HVIL_Status, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.HVIL_Status_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.HVIL_Status_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.HVIL_Status_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&IDLE_EVENT_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&IdleStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pIdleStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&InterruptStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_u2InterruptStackMaxBytesFree, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.IsolationLevel, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IsolationLevel_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IsolationLevel_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IsolationLevel_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.IsolationStatus, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IsolationStatus_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IsolationStatus_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IsolationStatus_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s17_motohawk_interpolation_2d, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.JCS_PackIdentifier_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.JCS_PackIdentifier_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.JCS_PackIdentifier_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&OSErrorDisplay, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&LinkStatus_ru1, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.lowAmperage, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&MatlabVersionTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Max_AmphoursIn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Max_AmphoursOut, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.MaxCellTemp, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellTemp_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellTemp_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s43_ReadCANMessage3_o3, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellTemperature_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellTemperature_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellTemperature_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellVoltage__Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellVoltage__Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s43_Gain1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellVoltage_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxCellVoltage_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s46_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxDisPwr_10s_Table, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.MaxDisPwr_10s_TableMap.data, 0xC0+0x30+0x0C+0x03, 0, CLASS_MAP, 77, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxDisPwr_Cont_Table, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.MaxDisPwr_Cont_TableMap.data, 0xC0+0x30+0x0C+0x03, 0, CLASS_MAP, 77, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumDischargePower_10s_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumDischargePower_10s_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s87_motohawk_interpolation_2d2, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumDischargePower_Continuos_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumDischargePower_Continuos_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s87_motohawk_interpolation_2d, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumRegenPower_10s_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumRegenPower_10s_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s87_motohawk_interpolation_2d3, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumRegenPower_Continuous_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaximumRegenPower_Continuous_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s87_motohawk_interpolation_2d1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxRegenPwr_10s_Table, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.MaxRegenPwr_10s_TableMap.data, 0xC0+0x30+0x0C+0x03, 0, CLASS_MAP, 77, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MaxRegenPwr_Cont_Table, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.MaxRegenPwr_Cont_TableMap.data, 0xC0+0x30+0x0C+0x03, 0, CLASS_MAP, 77, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MIL_Status_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MIL_Status_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MIL_Status_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.MILState, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.MinCellTemp, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellTemp_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellTemp_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s43_ReadCANMessage3_o4, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellTemperature_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellTemperature_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellTemperature_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellVoltage__Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellVoltage__Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s43_Gain2, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellVoltage_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MinCellVoltage_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s47_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.Capability, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&MotoHawkBuildGUID[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MotoHawkInterpolation2D, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.MotoHawkInterpolation2DMap.data, 0xC0+0x30+0x0C+0x03, 0, CLASS_MAP, 64, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&MotoHawkModelGUID[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&MotoHawkModelName[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.MotoHawkModelSecondsInUse, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&MotoHawkTokenGUID[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&MotoHawkVersionTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD_KeepAlive, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatile_NonVolatileCRC, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.NonVolatileFormatID, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&NonVolatileRestoreOnFirstStartup, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileRestoreOnStartup, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatile_NonVolatileStatus, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ONE_SECOND_EVENT_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&OSInternalErrorCnt_ru1, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&OSStatus, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.PackIdentifier, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PackState__Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PackState__Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s28_PackState, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PackState_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PackState_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s31_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.psPartNumber, 0x40+0x10+0x04+0x01, 1, CLASS_TEXT, 40, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&PasswordTxt[0], 0xC0+0x30+0x04+0x01, 0, CLASS_TEXT, 33, FLASH, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_u4PeakHeapBytesUsed, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.PPL_RollingCounter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.PPL10S_RollingCounter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PPL10s_RollingCounter_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PPL10s_RollingCounter_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PPL10s_RollingCounter_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PPLCont_RollingCounter_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PPLCont_RollingCounter_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PPLCont_RollingCounter_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Precharge_Current_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s45_DutyCycle, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 1, 2}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PreCharge_Duty_Cyle_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 1, 2}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PreCharge_Duty_Cyle_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PreCharge_Enable_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PreCharge_Enable_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s24_PreChargeEnable, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PreCharge_Freq_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PreCharge_Freq_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s88_DataTypeConversion3, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PrechargeState__Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PrechargeState__Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s29_state, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PrechargeState_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PrechargeState_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s30_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.ProcessorReboot, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&protocol_register_CAN_1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.PS_RollingCounter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PS_RollingCounter_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PS_RollingCounter_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PS_RollingCounter_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.PVC_RollingCounter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PVC_RollingCounter_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PVC_RollingCounter_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.PVC_RollingCounter_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&pwm_create_EST1_PWMOutput, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&pwm_set_EST1_PWMOutput, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Reset_AmpHoursIn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Reset_AmpHoursOut, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&resource_allocation, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.RestoreNVFactoryDefaults, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.SleepInhibited, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SleepInhibited_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SleepInhibited_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SleepInhibited_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.SOC_K, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOC_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOC_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s38_Switch, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s17_motohawk_interpolation_1d, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOC_PreLookupIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.SOC_PreLookupIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 11, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOC_PreLookupIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOC_TableIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.SOC_TableIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 4, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOC_TableIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOCMap, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.SOCMapTbl, 0xC0+0x30+0x0C+0x03, 0, CLASS_TBL, 4, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&STARTUP_EVENT_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfCharge_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfCharge_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s40_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.StateOfChargeMax, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargeMax_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargeMax_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargeMax_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.StateOfChargeMin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargeMin_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargeMin_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargeMin_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StoreNV, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_pSWISRCurrQueueSize, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&SystemFrequency_cu4, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, CODE, 0, 0, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.TAH_RollingCounter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.TAH_RollingCounter_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.TAH_RollingCounter_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.TAH_RollingCounter_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Temp_IR_PreIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Temp_IR_PreIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 8, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Temp_IR_PreIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&g_eTPUMaskType, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_u1TPUMaskVers, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.TrimpAmpHoursOut_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.TrimpAmpHoursOut_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s90_Sum1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.TripAmpsHoursIn_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.TripAmpsHoursIn_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s90_Sum, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&Unused_ru1, 0x40+0x00+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.V5V_Ref2, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.V5V_Reference_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.V5V_Reference_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s44_motohawk_ain1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Volt_IR_PreIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Volt_IR_PreIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 8, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Volt_IR_PreIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Voltage_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Voltage_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BatteryController_Rev1_B.s43_Gain, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.Wait_time, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.WakeSignal, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.WakeSignal_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.WakeSignal_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.WakeSignal_Prb, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 };

 const S_EriRequestTable Table2[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table3[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table4[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table5[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table6[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table7[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };



#include <Pragma_Section_End_rodata.h>

const S_EriReqTblList EriRequestTableList[8] =
{
 	{ Table0, 34 },
 	{ Table1, 362 },
 	{ Table2, 1 },
 	{ Table3, 1 },
 	{ Table4, 1 },
 	{ Table5, 1 },
 	{ Table6, 1 },
 	{ Table7, 1 },
 };


    
/* --- LOCAL FUNCTIONS ------------------------------------------------------------------------------------*/

S_EriReqTblList const* GetERIRequestTablePtr(uint1 table)
{
    return (&EriRequestTableList[table]);
}


