
/* file:/C:/Users/maxar/Documents/GitHub/Wisconsin-Hybrid/BuckyWagon_01/BuckyWagon_01_Build/TDB/TableDB.c */
/* Generated by MotoCoder */
/* Version: 0.12.4 */
/* At: 2019-04-29 19:22:21 */
/* Copyright: 2019 Woodward. */





#define  NO_TDB_PARSE
	
#define __TABLEDB_C
#define __TABLEDB_TDB
	


/* --- INCLUDE FILES --------------------------------------------------------------------------------------*/
	    
 #include "CommonInclude.h"
 #include "BuckyWagon_01.h"
 #include "TDB_Includes.h"
 
 

/* --- DEFINES -------------------------------------------------------------------------------------------*/
#ifndef __FAR_POINTER
    /* Define __FAR_POINTER as nothing */
    #define __FAR_POINTER
#endif
	    
/* var*/ 
 extern uint1 g_eProjectID;
 extern uint1 Table0Rev_cu1;
 extern uint1 Table1Rev_cu1;
 extern uint1 Table2Rev_cu1;
 extern uint1 g_u1KeyRev;
 extern uint1 g_u1EriRev;
 extern uint1 Table3Rev_cu1;
 extern uint1 Table4Rev_cu1;
 extern uint1 Table5Rev_cu1;
 extern uint1 Table6Rev_cu1;
 extern uint1 Table7Rev_cu1;
 extern uint4 g_u4ProductID;
 extern uint1 g_u1MotProgRev;
 extern S_ModuleConfig g_ConfigCopyObj;
 extern const Constant_T ConstantWork;
 extern BlockIO_BuckyWagon_01 BuckyWagon_01_B;
 extern Volatile_BSS_T VolatileWork_BSS;
 extern int32_T BGND_BASE_PERIODIC_RunCnt;
 extern int32_T BGND_BASEx10_PERIODIC_RunCnt;
 extern int32_T BGND_BASEx2_PERIODIC_RunCnt;
 extern int32_T BGND_BASEx20_PERIODIC_RunCnt;
 extern uint2 BgndStackMargin;
 extern uint4 g_pBgndStackMinBytesFree;
 extern NonVolatile_T NonVolatileWork;
 extern uint2 g_pu2IdlePerfTimerValue;
 extern uint2 CPUMargin;
 extern uint2 g_pCPUTime_AppISR;
 extern uint2 g_pu2BgndPerfTimerValue;
 extern uint2 g_pCPUTime_CAN;
 extern uint2 g_pu2FgndAnglePerfValue;
 extern uint2 g_pu2FgndTimePerfTimerValue;
 extern uint2 g_pCPUTime_MIOS;
 extern uint2 g_pCPUTime_Serial;
 extern uint2 g_pCPUTime_TimerISR;
 extern uint2 g_pCPUTime_TPU;
 extern int32_T FGND_10XRTI_PERIODIC_RunCnt;
 extern int32_T FGND_20XRTI_PERIODIC_RunCnt;
 extern int32_T FGND_2XRTI_PERIODIC_RunCnt;
 extern int32_T FGND_RTI_PERIODIC_RunCnt;
 extern uint4 g_pu4FgndAngleStackMinBytesFree;
 extern uint2 FgndTimeStackMargin;
 extern uint4 g_pFgndTimeStackMinBytesFree;
 extern uint32_T GaugeChain_EZLinkCallbackCounter;
 extern uint32_T GaugeChain_EZLinkNoPendingTxCounter;
 extern uint2 HeapMargin;
 extern int32_T IDLE_EVENT_RunCnt;
 extern uint2 IdleStackMargin;
 extern uint4 g_pIdleStackMinBytesFree;
 extern uint2 InterruptStackMargin;
 extern uint2 g_u2InterruptStackMaxBytesFree;
 extern uint1 LinkStatus_ru1;
 extern uint8_T MaxQueueDepth;
 extern uint32_T NonVolatile_NonVolatileCRC;
 extern int32_T ONE_SECOND_EVENT_RunCnt;
 extern uint1 OSInternalErrorCnt_ru1;
 extern uint4 g_u4PeakHeapBytesUsed;
 extern int32_T SHUTDOWN_EVENT_RunCnt;
 extern int32_T STARTUP_EVENT_RunCnt;
 extern uint1 g_pSWISRCurrQueueSize;
 extern uint4 SystemFrequency_cu4;
 extern uint1 g_u1TPUMaskVers;
 extern uint1 Unused_ru1;
 
 /* text*/ 
 extern uint1 SwIdTxt[];
 extern uint1 CalIdTxt[];
 extern uint1 SwRevisionTxt[];
 extern uint1 FriendlyName[];
 extern uint1 CompilerVersion[];
 extern uint1 ControlCoreSDKRelease[];
 extern uint1 MatlabVersionTxt[];
 extern uint1 MotoHawkBuildGUID[];
 extern uint1 MotoHawkModelGUID[];
 extern uint1 MotoHawkModelName[];
 extern uint1 MotoHawkTokenGUID[];
 extern uint1 MotoHawkVersionTxt[];
 extern uint1 PasswordTxt[];
 
 /* array*/ 
 extern S_HardwareCompatibilityEntry ApplicationCompatibilityArr[];
 
 /* enum*/ 
 extern E_NativeFWError ain_create_Accel_Pedal_Pin;
 extern E_NativeFWError ain_create_Brake_Pedal_Pin;
 extern E_NativeFWError ain_create_ECUP;
 extern E_NativeFWError ain_create_LV_Voltage_Pin;
 extern E_NativeFWError ain_create_Reverse_Switch_Pin;
 extern E_NativeFWError ain_read_Accel_Pedal_Pin;
 extern E_NativeFWError ain_read_Brake_Pedal_Pin;
 extern E_NativeFWError ain_read_ECUP;
 extern E_NativeFWError ain_read_LV_Voltage_Pin;
 extern E_NativeFWError ain_read_Reverse_Switch_Pin;
 extern E_ApplicationInitStatus ApplicationInitStatus;
 extern E_ApplicationMonitorEnable ApplicationMonitorEnable;
 extern E_ApplicationInitStatus ApplicationPausePoint;
 extern E_ApplicationStatus ApplicationStatus;
 extern uint32_T ApplicationStopReason;
 extern uint32_T ApplicationStopReasonBlock;
 extern uint2 g_u1BgndAngSchdLateFlags;
 extern uint1 g_u1BgndTimeSchdLateFlags;
 extern E_NativeFWError can_create_CAN_1;
 extern E_NativeFWError can_create_CAN_2;
 extern E_NativeFWError can_tx_err_CAN_1_0;
 extern E_NativeFWError can_tx_err_CAN_1_0_27;
 extern E_NativeFWError can_tx_err_CAN_2_0;
 extern E_NativeFWError can_tx_err_CAN_2_0_28;
 extern E_NativeFWError din_create_EStop_Switch_Pin;
 extern E_NativeFWError din_read_EStop_Switch_Pin;
 extern E_NativeFWError dout_create_DOut177p001;
 extern E_NativeFWError dout_create_DOut178p001;
 extern E_NativeFWError dout_create_DOut179p001;
 extern E_NativeFWError dout_create_DOut3919p0004;
 extern uint2 g_u1FgndAngSchdLateFlags;
 extern S_SetDisplayInfo FWModulesSetDisplayInfo;
 extern E_NativeFWError GaugeChain_EZlinkTx;
 extern E_OSInternalErrorType OSErrorDisplay;
 extern E_NativeFWError mh_EZlink;
 extern uint8_T NonVolatileRestoreOnFirstStartup;
 extern uint8_T NonVolatileRestoreOnStartup;
 extern uint8_T NonVolatile_NonVolatileStatus;
 extern E_OSStatus OSStatus;
 extern E_NativeFWError protocol_register_CAN_1;
 extern E_NativeFWError pwm_create_Fan_Pin_PWMOutput;
 extern E_NativeFWError pwm_set_Fan_Pin_PWMOutput;
 extern E_NativeFWError resource_allocation;
 extern uint1 g_eTPUMaskType;
 
 /* prelookup*/ 
 
 /* interpolation_1d*/ 
 
 /* bitfield*/ 
 extern S_CCPHandlerInstance mh_CCP1_CCPHandlerInstance;
 extern uint4 CodeCoveredBits[];
 
 /* enumarr*/ 
 extern Volatile_T VolatileWork;
 
 /* interpolation_2d*/ 
 


#include <Pragma_Section_Start_ERIToolsTable_rodata.h>

const S_EriRequestTable Table0[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table0Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table1Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table2Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_u1KeyRev, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_u1EriRev, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table3Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table4Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table5Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table6Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&Table7Rev_cu1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&SwIdTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 13, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&CalIdTxt[0], 0xC0+0x30+0x0C+0x03, 0, CLASS_TEXT, 33, FLASH, 0, 1, 1}, 
 {(void* __FAR_POINTER)&SwRevisionTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&FriendlyName[0], 0xC0+0x30+0x04+0x01, 0, CLASS_TEXT, 33, FLASH, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_u4ProductID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&g_u1MotProgRev, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.BootVerMaj, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.BootVerMin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.EcuHwMaj, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.EcuHwMin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationCompatibilityArr[0], 0x40+0x10+0x04+0x01, 0, CLASS_ARRAY, 50, CODE, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.psSerialNumber, 0x40+0x10+0x04+0x01, 1, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.psModelNumber, 0x40+0x10+0x04+0x01, 1, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 };

 const S_EriRequestTable Table1[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&ConstantWork.A123_Isolation_Monitor_Ground_Fault_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_ABC_Phase_Order, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s20_motohawk_ain, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_DfltValue, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_FilterConst, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_Full, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_InputHiFltPos, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_InputLoFltPos, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s337_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Accel_Pedal_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Accel_Pedal_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_Pedal_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_Pedal_Pin_ref, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s216_Saturation, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Accel_Zero, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s108_LogicalOperator, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Acceleration_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Acceleration_Limited, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.AccelPedalMap_v2, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.AccelPedalMap_v2Idx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.AccelPedalMap_v2IdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 13, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.AccelPedalMap_v2In, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.AccelPedalMap_v2Tbl, 0xC0+0x30+0x0C+0x03, 0, CLASS_TBL, 13, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.AccelRstSpd, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.AccelRstThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Accurate_Current, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Accurate_Speed, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Accurate_Torque, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Accurate_Voltage, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_ADC_Calibration_Problem, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_ADC_Calibration_Problem_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_AgeCount, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ain_create_Accel_Pedal_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_create_Brake_Pedal_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_create_ECUP, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_create_LV_Voltage_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_create_Reverse_Switch_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_Accel_Pedal_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_Brake_Pedal_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_ECUP, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_LV_Voltage_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ain_read_Reverse_Switch_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Allow_MainContactor_Close, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Angular_Distance, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ApplicationInitStatus, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationMonitorEnable, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationPausePoint, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationStatus, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ApplicationStopReason, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ApplicationStopReasonBlock, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Bad_Position_Signal, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Bad_Switch, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Batt_Load_Enable, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Battery_OverTemp_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Battery_UnderTemp_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_alarm, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_cell_overvolt_ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_cell_overvolt_ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s229_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cell_tmax, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cell_tmin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cell_undervolt, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cell_vmax, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cell_vmin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_chargec_stat_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_chargec_stat_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_chg_buf, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_chg_done, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_chg_max, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_chga_ena, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_chga_mon, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s228_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cool_req, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cpwr_cmd, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_cpwr_mon, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_dis_buf, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_dis_max, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_epo, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_gfd, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_hvil_mon, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_ibat, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_lvbat, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s227_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_mainc_stat_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_mainc_stat_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_mod_ena, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s231_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_ready_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.bcm_ready_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_soc_j, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_t_coolant, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_vbat, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_veh_mon, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BGND_BASE_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&BGND_BASEx10_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&BGND_BASEx2_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&BGND_BASEx20_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&g_u1BgndAngSchdLateFlags, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BgndStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pBgndStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&g_u1BgndTimeSchdLateFlags, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_Active_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s20_motohawk_ain1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_DfltValue, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_FilterConst, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_Full, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_InputHiFltPos, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_InputLoFltPos, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_light_On_Setpoint, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_Light_Out, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s353_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Brake_Pedal_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Brake_Pedal_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_Pedal_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_Pedal_Pin_ref, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s218_Saturation, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Brake_Zero, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.brakeTime_sec, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_ext_handled_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_ext_last_unhandled_id, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_ext_receive_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_std_handled_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_std_last_unhandled_id, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_1_std_receive_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_2_ext_handled_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_2_ext_last_unhandled_id, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_2_ext_receive_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_2_std_handled_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_2_std_last_unhandled_id, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_2_std_receive_count, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&can_create_CAN_1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&can_create_CAN_2, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_CAN_Limits_In_Effect, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&can_tx_err_CAN_1_0, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&can_tx_err_CAN_1_0_27, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&can_tx_err_CAN_2_0, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&can_tx_err_CAN_2_0_28, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.CAN_Watchdog_Reset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.cCInd_LongOff, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.cCInd_OnTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.cCInd_ShortTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&mh_CCP1_CCPHandlerInstance.UnlockStatus, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&mh_CCP1_CCPHandlerInstance.Connected, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP1_StationAddr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP1RxID, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP1RxIDMask, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.CCP1TxID, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Charge_Complete_Override_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Charge_Complete_Override_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s81_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Charge_Enable_Override_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Charge_Enable_Override_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s82_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Charge_Falt_Override_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Charge_Falt_Override_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s80_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.ChargeComplete_SOC, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.ChargeInterruptor_Voltage, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Charger_Temp_Enable, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Charger_Temp_Offset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_ChargerState, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.ChargerState_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.ChargerState_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.CityID_CAN_1, 0xC0+0x00+0x00+0x00, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s132_Product2, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[0], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[1], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[2], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[3], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&CodeCoveredBits[4], 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Command_Counter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&CompilerVersion[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.u1ConfigVerMaj, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.u1ConfigVerMin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Contactor_Disable_Delay, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Contactor_Shutdown_Test_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Contactor_Shutdown_Test_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Control_Mode, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ControlCoreSDKRelease[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coolant_Fan, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coolant_FanIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Coolant_FanIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 10, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coolant_FanIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Coolant_FanTbl, 0xC0+0x30+0x0C+0x03, 0, CLASS_TBL, 10, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coolant_Pump, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coolant_PumpIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Coolant_PumpIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 10, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Coolant_PumpIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Coolant_PumpTbl, 0xC0+0x30+0x0C+0x03, 0, CLASS_TBL, 10, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s119_Switch, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Counter_Mode_Select, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Counter_Multiplier, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s93_Switch, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&g_pu2IdlePerfTimerValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&CPUMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_AppISR, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pu2BgndPerfTimerValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_CAN, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pu2FgndAnglePerfValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pu2FgndTimePerfTimerValue, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_MIOS, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_Serial, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_TimerISR, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pCPUTime_TPU, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.creepSpeed, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Current_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Current_Limit_Override_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Current_Limit_Override_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s78_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Current_Transducer_Fault_IbusIleg, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s210_bcm_vbat, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.DCDCInhibit_Out_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&din_create_EStop_Switch_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&din_read_EStop_Switch_Pin, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.DisplayFaults, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.dispLength, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut177p001, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut178p001, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut179p001, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&dout_create_DOut3919p0004, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Downsample, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Drive_Enable_Delay, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_RelationalOperator, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.dualIndex, 0xC0+0x30+0x0C+0x03, 0, CLASS_ARRAY, 2, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.E_Stop_Invert, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Eaton_HV_Charger_Temperature_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Eaton_HV_Charger_Temperature_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_Eaton_HV_Charger_Temperature, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s314_pluggedIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.ECUP_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_brakeEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_driveEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_driveNbrakeEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_EHPAS_Fault, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Fault_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Fault_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_IdleEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_EHPAS_Input_Current_NA, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Input_Current_NA_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Input_Current_NA_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_EHPAS_Input_Voltage, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Input_Voltage_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Input_Voltage_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_keyUpEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_lowSpeedEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_EHPAS_Op_State, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Op_State_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Op_State_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Operating_Mode_Cmd_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Operating_Mode_Cmd_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s23_OperatingMode_cmd, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_Performance_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_EHPAS_Pump_Speed, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Pump_Speed_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_Pump_Speed_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s139_PumpState, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_PumpStateEnable_ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_PumpStateEnable_ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_slowingEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.EHPAS_stoppingEn, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_EHPAS_TempCur, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_TempCur_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_TempCur_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s212_EHPAS_TempMax, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_TempMax_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EHPAS_TempMax_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s213_EMP_Board_Temp, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Board_Temp_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Board_Temp_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.EMP_CAN_MaxAge, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s214_EMP_Board_Temp, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Board_Temp_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Board_Temp_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s214_EMP_Pump_Mode, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Mode_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Mode_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s214_EMP_Pump_Power, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Power_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Power_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s214_EMP_Pump_Speed, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Speed_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Speed_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s214_EMP_Speed_Percent, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Speed_Percent_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Speed_Percent_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s214_EMP_Pump_Status, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Status_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Cooling_Fan_Status_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s75_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Fan_Speed_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Fan_Speed_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Mode_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Mode_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s213_EMP_Pump_Mode, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Mode_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Mode_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s213_EMP_Pump_Power, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Power_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Power_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s213_EMP_Pump_Speed, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Speed_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Speed_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s213_EMP_Pump_Status, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Status_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Pump_Status_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s69_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Speed_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Speed_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s213_EMP_Speed_Percent, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Speed_Percent_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.EMP_Speed_Percent_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.EMPFan_CAN_MaxAge, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Enable_Brake_Light_Out, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Enable_Coast_Neg_Torque, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Enable_PowerSteering_CAN_Msg, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Enable_Regen, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Estop_switch_ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Estop_switch_ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.EStop_Switch_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s223_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Fan_Hold_Mode, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Fan_Mode, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Fan_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s60_MinMax1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.FanOut_Frequency, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.FanOut_Gain, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.FanOut_MaxLimit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.FanOut_MinLimit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FanOut_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.FanOut_Offset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FanOut_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork.FaultActionReason, 0x40+0x10+0x04+0x01, 0, CLASS_ENUMARR, 7, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.FaultCommand, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.FaultManager[0], 0xC0+0x30+0x0C+0x03, 0, CLASS_ENUMARR, 429, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&NonVolatileWork.FaultMarquees[0], 0x40+0x10+0x04+0x01, 0, CLASS_ENUMARR, 3, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_FaultSeverityIndicator, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FaultSeverityIndicator_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.FaultSeverityIndicator_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&FGND_10XRTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&FGND_20XRTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&FGND_2XRTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&FGND_RTI_PERIODIC_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&g_pu4FgndAngleStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&g_u1FgndAngSchdLateFlags, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&FgndTimeStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pFgndTimeStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.firstScrollTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Flash_Reverse_Lights_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Flash_Reverse_Lights_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s51_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Forced_Open_Loop, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Forced_Voltage_Control, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Forward_Speed_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&FWModulesSetDisplayInfo.DisplayVar, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.fwdAccThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.fwdSpdThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&GaugeChain_EZLinkCallbackCounter, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&GaugeChain_EZLinkNoPendingTxCounter, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&GaugeChain_EZlinkTx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.GFD_Enable, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.GFD_Torque_Off, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.hardBrakeLev, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&HeapMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Heartbeat_Identifier_1, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Heartbeat_Identifier_2, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_High_Bound, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.High12VThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_enable, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_enable_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_enable_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s21_Switch, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_epo_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_epo_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s28_LogicalOperator, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_leakage_enable_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_leakage_enable_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s123_LogicalOperator, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_mainc_enable_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.hsc_bcm_mainc_enable_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.HV_Bus_allowed_mismatch, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.HV_Bus_offline_delay, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.HV_GFI_Check, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&IDLE_EVENT_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&IdleStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_pIdleStackMinBytesFree, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_IgnitionStatus, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IgnitionStatus_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.IgnitionStatus_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Ignore_Accel_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s157_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.In_Reverse_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.In_Reverse_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s47_LogicalOperator, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InhibitDCDC_Out__new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InhibitDCDC_Out__ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.InhibitDCDC_Out__Polarity, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InputCurrent_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InputCurrent_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_InputCurrentLimitMax, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InputCurrentLimitMax_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InputCurrentLimitMax_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InputVoltage_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InputVoltage_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Gain1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.InstDCDCWatts, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Gain4, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Gain5, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Gain6, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Gain, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Saturation, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.IntermediaryGearRatio, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&InterruptStackMargin, 0xC0+0x30+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_u2InterruptStackMaxBytesFree, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s115_Switch1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Invalid_Power_Supply, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Inverter_Fault, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Inverter_Fault_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Inverter_Fault_Occured, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Iverter_Fault_Occured_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Inverter_Over_Temperature_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Inverter_Over_Temperature, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Inverter_Temp_Enable, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Inverter_Temp_Offset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Inverter_Temperature, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.InverterTemp_Overheat, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.InvertMode, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Gain3, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Gain8, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.KeyOnRuntime_Sec, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&OSErrorDisplay, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.lastScrollTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Leg_Current, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Limits_Control_Mode, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Limp_Home_Mode, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Limp_Home_Mode_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&LinkStatus_ru1, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.listIndex, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Load_Enable_Delay, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Low_Bound, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Low12VThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.LowSpeedManeuverRuntime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.LV_Voltage_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.LV_Voltage_Pin_ref, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s345_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s20_motohawk_ain5, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.LVVolt_DfltValue, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.LVVolt_FilterConst, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.LVVolt_Gain, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.LVVolt_InputHiFltPos, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.LVVolt_InputLoFltPos, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.LVVolt_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.LVVolt_Ofst, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.LVVolt_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s217_Sum1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_InputCurrent, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_InputVoltage, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&MatlabVersionTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Max_Coast_Tq, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Max_Regen_Tq, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Max_Slect_Tq_drive, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Max_SOC_For_Coast_Tq_EN, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&MaxQueueDepth, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_MessageChecksum, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_MessageCounter, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&mh_EZlink, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s126_Sum, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Min_Speed_Allow_Coast_NegT, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.minPumpRunTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.minTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s191_minTimer, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.Capability, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, CODE, 0, 0, 1}, 
 {(void* __FAR_POINTER)&MotoHawkBuildGUID[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&MotoHawkModelGUID[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&MotoHawkModelName[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.MotoHawkModelSecondsInUse, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&MotoHawkTokenGUID[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 80, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&MotoHawkVersionTxt[0], 0x40+0x10+0x04+0x01, 0, CLASS_TEXT, 50, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Derate, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Not_Enabled, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Not_Enabled_Histroy, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Shutdown, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Motor_Stalled, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s143_Sum1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.motor_torque_Ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.motor_torque_Ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MotorSpdIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.MotorSpdIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 8, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MotorSpdIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD_KeepAlive, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.MPRD_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.noErrText[0], 0xC0+0x30+0x0C+0x03, 0, CLASS_TEXT, 10, FLASH, 0, 1, 1}, 
 {(void* __FAR_POINTER)&NonVolatile_NonVolatileCRC, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.NonVolatileFormatID, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&NonVolatileRestoreOnFirstStartup, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileRestoreOnStartup, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatile_NonVolatileStatus, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.offTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ONE_SECOND_EVENT_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.onTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&OSInternalErrorCnt_ru1, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&OSStatus, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_OutputCurrent, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.OutputCurrent_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.OutputCurrent_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s215_OutputVoltage, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.OutputVoltage_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.OutputVoltage_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Bus_Current, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Bus_Current_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Leg_Current, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Leg_Current_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Phase_Advance, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Phase_Advance_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Over_SOC_Shutdown_Thresh, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Over_SOCAlertThresh, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Speed_Alarm, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Speed_Alarm_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Speed_Warning, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Speed_Warning_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Voltage_Alarm, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Voltage_Alarm_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Voltage_Warning, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Over_Voltage_Warning_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Overheat_PumpFan_Speed, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Overheat_Threshold, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&g_ConfigCopyObj.psPartNumber, 0x40+0x10+0x04+0x01, 1, CLASS_TEXT, 40, CODE, 0, 1, 1}, 
 {(void* __FAR_POINTER)&PasswordTxt[0], 0xC0+0x30+0x04+0x01, 0, CLASS_TEXT, 33, FLASH, 0, 1, 1}, 
 {(void* __FAR_POINTER)&g_u4PeakHeapBytesUsed, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Phase_Current_Sensor_Error, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.PluggedInHistTimeeaton, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.PluggedInMainsThesEaton, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Power_Switches_Off, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s17_Motor_Torque, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.ProcessorReboot, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&protocol_register_CAN_1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&pwm_create_Fan_Pin_PWMOutput, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&pwm_set_Fan_Pin_PWMOutput, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.quadIndex, 0xC0+0x30+0x0C+0x03, 0, CLASS_ARRAY, 4, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s119_Switch1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s132_Product, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.RearDiffRatio, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Regen_Full, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Regen_SOC_Speed_Ramp_ovr_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Regen_SOC_Speed_Ramp_ovr_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s132_Saturation1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Regen_Start, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Regen_Switch_Open, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.RegenBatteryLimits, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.RegenBatteryLimitsMap.data, 0xC0+0x30+0x0C+0x03, 0, CLASS_MAP, 32, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&resource_allocation, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.RestoreNVFactoryDefaults, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.revAccThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Reverse_Polarity, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Reverse_Speed_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s242_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Reverse_Switch_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Reverse_Switch_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Reverse_Switch_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.Reverse_Switch_Pin_ref, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s211_DataTypeConversion, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Reverse_SwitchPt, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Reverse_TQ_Negative_Enable, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.ReverseIndFlash_Period, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.ReverseOut_Pin, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 1, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.RevIndType, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s46_LogicalOperator, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.RevOut__new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.RevOut__ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.RevOut__Polarity, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.revSpdThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Rotor_Over_Temperature, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Rotor_Over_Temperature_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Rotor_Temp, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Rotor_Temp_Enable, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Rotor_Temp_Offset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.screen, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s191_scrollIndex, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.scrollTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s191_scrollTimer, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&SHUTDOWN_EVENT_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Shutdown_Req, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&NonVolatileWork.singleIndex, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork.SOC_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.SOC_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Software_Release_Major_Version, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Software_Release_Minor_Version, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Software_Release_Sub_Version, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Stall_Safety_Percentage, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.StallSpd, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.StallTrqThres, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&STARTUP_EVENT_RunCnt, 0xC0+0x30+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.startupCount, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.startupDelay, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargePctIdx, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.StateOfChargePctIdxArr, 0xC0+0x30+0x0C+0x03, 0, CLASS_ORDARR, 4, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StateOfChargePctIn, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Stator_Over_Temperature, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Stator_Over_Temperature_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Stator_Temp, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Stator_Temp_Enable, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Stator_Temp_Offset, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Status_A, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Status_C, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.stopSpeed, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.StoreNV, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Suge_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&g_pSWISRCurrQueueSize, 0x40+0x10+0x00+0x00, 1, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_System_Disabled_In_Motion, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&SystemFrequency_cu4, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, CODE, 0, 0, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Temp_ped_switchOver, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s357_Sum, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.TireSize, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Torque_Desired, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.TorqueRequestLP, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&NonVolatileWork.totalOnTime, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 4}, 
 {(void* __FAR_POINTER)&g_eTPUMaskType, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&g_u1TPUMaskVers, 0x40+0x10+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Turbo_Mode, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Under_SOC_Shutdown_Thresh, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Under_SOCAlertThresh, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Under_Voltage_Warning, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Under_Voltage_Warning_History, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&Unused_ru1, 0x40+0x00+0x00+0x00, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s96_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.UQM_Direction_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.UQM_Direction_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s94_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.UQM_Enable_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.UQM_Enable_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s95_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.UQM_Torque_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.UQM_Torque_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.UQM_TurboMode, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Use_Raw_Speed, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Using_Raw_Speed, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.VDO_Gauge_Brightness, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 0, 0, 2}, 
 {(void* __FAR_POINTER)&ConstantWork.VDO_Gauge_StartupDelay, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Veh_Speed_Regen_Filter, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s126_Sum1, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s362_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Vehicle_Speed_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Vehicle_Speed_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&ConstantWork.Voltage_Limit, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Voltage_Limit_Override_new, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&VolatileWork_BSS.Voltage_Limit_Override_ovr, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, RAM, 0, 0, 1}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s79_Merge, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Watchdog_Error, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&ConstantWork.Watchdog_Reset_Num, 0xC0+0x30+0x0C+0x03, 0, CLASS_VAR, 1, FLASH, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s221_Command_Watchdog_Status, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Divide, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 {(void* __FAR_POINTER)&BuckyWagon_01_B.s127_Divide3, 0x40+0x10+0x04+0x01, 0, CLASS_VAR, 1, RAM, 1, 1, 4}, 
 };

 const S_EriRequestTable Table2[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table3[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table4[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table5[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table6[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };

 const S_EriRequestTable Table7[] __SECTION_ERITOOLSTABLE_RODATA__ =
{
 {(void* __FAR_POINTER)&g_eProjectID, 0xC0+0x10+0x04+0x01, 0, CLASS_VAR, 1, FLASH, 0, 0, 1}, 
 };



#include <Pragma_Section_End_rodata.h>

const S_EriReqTblList EriRequestTableList[8] =
{
 	{ Table0, 34 },
 	{ Table1, 653 },
 	{ Table2, 1 },
 	{ Table3, 1 },
 	{ Table4, 1 },
 	{ Table5, 1 },
 	{ Table6, 1 },
 	{ Table7, 1 },
 };


    
/* --- LOCAL FUNCTIONS ------------------------------------------------------------------------------------*/

S_EriReqTblList const* GetERIRequestTablePtr(uint1 table)
{
    return (&EriRequestTableList[table]);
}


